export const blackListedComponents = [
  // React Native primitive components
  'View',
  'ScrollView',
  'TextInput',
  'TouchableOpacity',
  'TouchableHighlight',
  'TouchableWithoutFeedback',
  'Pressable',
  //   'SafeAreaView',
  //   'FlatList',
  //   'SectionList',
  //   'ActivityIndicator',
  'Modal',
  'StatusBar',
  'Switch',
  //   'RefreshControl',
  //   'KeyboardAvoidingView',
  //   'DrawerLayoutAndroid',
  //   'ProgressBarAndroid',
  //   'ToolbarAndroid',
  'ImageBackground',
  //   'VirtualizedList',
  'Text',
  'Image',
];
